services:
  langgraph-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: langgraph_data_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
